{
 "title": "micro-services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(http_requests_in_flight,container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Throughput (req/s)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(received_request_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(processed_request_total{container=\"$container\"}[5m]) * 100) / rate(received_request_total{container=\"$container\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_errors_total[5m])) / sum(rate(received_request_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Active Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_flight{container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(received_request_total{container=\"$container\"}[5m])",
     "legendFormat": "Total requests received"
    },
    {
     "expr": "rate(processed_request_total{container=\"$container\"}[5m])",
     "legendFormat": "Total requests processed"
    }
   ]
  },
  {
   "title": "Error Rate by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(error_type) (rate(request_errors_total{container=\"$container\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{container=\"$container\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50 Latency by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}