name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor]
  patch:
    labels: [patch]
  default: patch

categories:
  - title: '🚨 Breaking'
    labels: [major]
  - title: '✨ Features'
    labels: [minor]
  - title: '🐛 Fixes'
    labels: [patch]

change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
