apiVersion: v1
kind: Service
metadata:
  name: web-server-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
