# This ClusterSecretStore will use IRSA by default to access SecretsManager.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: my-cluster-secret-store
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-3 #TODO: variablilize 
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
