apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-cluster-secret-store 
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: my_postgres
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: my_postgres
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: my_postgres
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: my_postgres
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: my_postgres
        property: dbname
