apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default

  selector:
    matchLabels:
      monitoring: http-metrics
  
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http
      scrapeTimeout: 10s
      honorLabels: true
