services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/pg
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Containerfile
    image: api:latest
    container_name: api
    env_file: .env
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
