FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o api

FROM scratch AS runner

COPY --from=builder /app/api ./api

EXPOSE 3030

CMD [ "/api" ]
