FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o api


# https://images.chainguard.dev/directory/image/static/versions 
# ultra minimal image for running static binaries in production
FROM cgr.dev/chainguard/static:latest AS runner

COPY --from=builder /app/api ./api

EXPOSE 3030

CMD [ "/api" ]
