name: 'api Build & Push'
on:
  pull_request:
    paths:
      - 'apps/api/**'
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      run: |
        docker build ./apps/api/ -t api -f apps/api/Containerfile
        
        if [ "$IS_MAIN_BRANCH" = "true" ]; then
          # Push to production repo
          docker tag api:latest $ECR_REGISTRY/api-prod:latest
          docker tag api:latest $ECR_REGISTRY/api-prod:v${{ github.run_number }}
          docker push $ECR_REGISTRY/api-prod:latest
          docker push $ECR_REGISTRY/api-prod:v${{ github.run_number }}
        else
          # Push to shared dev
          BRANCH_NAME=$(echo "${{ github.ref_name }}")
          docker tag api:latest $ECR_REGISTRY/dev:api-$BRANCH_NAME
          docker push $ECR_REGISTRY/dev:api-$BRANCH_NAME
        fi
