name: 'build-push-prod'

on:
  release:
    types: [published]

jobs:
  release-build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{github.ref_name}} 
      run: |
          docker build ./apps/api/ -t api -f apps/api/Containerfile
          docker build ./apps/web-server/ -t web-server -f apps/web-server/Containerfile

          docker tag api:latest $ECR_REGISTRY/api-prod:$TAG
          docker tag web-server:latest $ECR_REGISTRY/web-server-prod:$TAG

          docker push $ECR_REGISTRY/api-prod:$TAG
          docker push $ECR_REGISTRY/web-server-prod:$TAG
