name: 'lint-build-push-dev'
on:
  pull_request:
    paths:
      - 'apps/*/**'

jobs:
  lint-format:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service: [api, web-server]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Lint & Format
        uses: ./.github/actions/lint-format
        with:
          service: ${{ matrix.service }}

  build-push-dev:
    needs: lint-format
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service: [api, web-server]
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image
        uses: ./.github/actions/branch-build-push
        with:
          service: ${{ matrix.service }}
          ecr-registry: ${{ steps.ecr-login.outputs.registry }}
          branch-name: ${{ github.head_ref || github.ref_name }}
