name: Release and Deploy to Prod

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - id: drafter
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: get_tag
        run: |
          if [ -n "${{ steps.drafter.outputs.tag_name }}" ]; then
            echo "tag=${{ steps.drafter.outputs.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

  build-push-prod:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, web-server]
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image
        uses: ./.github/actions/branch-build-push
        with:
          service: ${{ matrix.service }}
          ecr-registry: ${{ steps.ecr-login.outputs.registry }}
          branch-name: ${{ needs.release.outputs.release_tag }} 
