name: Require semver label

on:
  pull_request:
    types: 
      - labeled
      - unlabeled
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const labels = (context.payload.pull_request.labels || []).map(l => l.name)
            const allowed = ['major','minor','patch']
            const ok = labels.some(l => allowed.includes(l))
            if (!ok) {
              core.setFailed(`Add one of these labels to this PR: ${allowed.join(', ')}`)
            }
