name: 'web-server Build & Push'
on:
  pull_request:
    paths:
      - 'apps/web-server/*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      run: |
        docker build ./apps/web-server/ -t api -f apps/web-server/Containerfile
        docker tag api:latest $ECR_REGISTRY/web-server:$BRANCH_NAME
        docker push $ECR_REGISTRY/web-server:$BRANCH_NAME
