singleBinary:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: monitoring
      operator: Equal
      value: "true"
      effect: NoSchedule
  persistence:
    enabled: true
    size: 10Gi

# Disable distributed mode
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
